version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # Ou outra versão compatível
    commands:
      - echo "Instalando OWASP Dependency-Check..."
      - curl -sLO https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
      - unzip dependency-check-9.0.9-release.zip
      - export PATH=$PATH:$(pwd)/dependency-check/bin

  build:
    commands:
      - echo "Limpando banco de dados local..."
      - dependency-check.sh --purge
      - echo "Rodando análise de dependências..."
      - mkdir -p reports/
      - dependency-check.sh --project "meu-projeto" --scan . --format HTML --out reports/ --nvdApiKey 4a090b91-1ff3-46ec-96be-beaa3528f734 --nvdApiDelay 10000

  post_build:
    commands:
      - echo "Análise concluída! Verificando se o diretório reports/ existe..."
      - if [ -d "reports/" ]; then aws s3 cp reports/ s3://codepipeline-us-east-2-106173377886/ --recursive; else echo "Diretório reports/ não encontrado."; fi