version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # Ou outra versão compatível
    commands:
      - echo "Instalando OWASP Dependency-Check..."
      - curl -sLO https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
      - unzip dependency-check-9.0.9-release.zip
      - export PATH=$PATH:$(pwd)/dependency-check/bin

  build:
    commands:
      - echo "Rodando análise de dependências..."
      - dependency-check.sh --project "meu-projeto" --scan . --format HTML --out reports/

  post_build:
    commands:
      - echo "Análise concluída! Salvando resultados..."
      - aws s3 cp reports/ s3:/laddevops/ --recursive